name: deniz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  url_launcher: ^5.7.10
  carousel_slider: ^2.3.1
  google_maps_flutter: ^1.0.6
  dio: ^3.0.10
  shared_preferences: ^0.5.12+4
  get:
  shimmer: ^1.1.2
  intl:
  flutter_svg:
  sqflite: ^1.3.2+2
  path:
  flutter_spinkit: ^4.1.2+1
  video_player: ^1.0.1
    # git:
    #   url: https://github.com/sanekyy/plugins.git
    #   ref: caching
    #   path: packages/video_player/video_player
  # provider: ^4.3.3
  flutter_slidable: ^0.5.7
  path_provider: ^1.6.27
  mime: ^0.9.7
  provider: ^4.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line
  flutter_native_splash: ^0.2.8

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/logo.png"
  image_path_android: "assets/launcher/logo.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/launcher/logo.png"

flutter_native_splash:
  # color is the only required parameter.  It sets the background color of your splash screen.
  color: "#ffffff"
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specifiy an image used in the splash screen.  It must be a
  # png file.
  image: assets/launcher/logo.png

  # The color_dark and image_dark are parameters that set the color and image when the device is
  # in dark mode.  If they are not specified, the app will use the color and image above.
  # If the image_dark parameter is specified, color_dark must be specified.
  # color_dark: "#042a49"
  # image_dark: assets/splash-invert.png

  # The android and ios parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: true

  # The position of the splash image can be set with android_gravity and ios_content_mode
  # parameters.  Both default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center

  # To display the notification bar on Android, use the android_disable_fullscreen parameter.
  #android_disable_fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        # - asset: assets/fonts/Montserrat-BlackItalic.ttf
        #   weight: 900
        #   style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        # - asset: assets/fonts/Montserrat-HeavyItalic.ttf
        #   weight: 800
        #   style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        # - asset: assets/fonts/Montserrat-BoldItalic.ttf
        #   weight: 700
        #   style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        # - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        #   weight: 600
        #   style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        # - asset: assets/fonts/Montserrat-RegularItalic.ttf
        #   style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
